networks:
  fdo_network:
    external: true

volumes:
  # O padrão proficional de persistência é por bind mount, mas para facilitar o uso em ambientes de desenvolvimento
  # e testes que rodam em Windows, utilizamos um "volume nomeado" gerenciado pelo Docker.
  db_data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0 --port=8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fdo_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: supervisord -c /var/www/html/docker/supervisor/worker.conf
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fdo_network

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan reverb:start --host=${REVERB_SERVER_HOST:-0.0.0.0} --port=${REVERB_SERVER_PORT:-8081}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fdo_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/nginx.dockerfile
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
      reverb:
        condition: service_started
    env_file:
      - .env
    networks:
      - fdo_network

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    networks:
      - fdo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    # Exemplo de bind mount para persistência local:
    # - /srv/fdo/volumes/mysql:/var/lib/mysql
    # Obs: Ao utilizar bind mount em Windows, certifique-se de que o diretório existe e possui as permissões corretas.
  
  migrate:
    # Por questões de segurança, a porta 3306 do MySQL não é exposta para fora do container.
    # Este serviço é responsável por aplicar as migrações no banco de dados de dentro da rede do Docker, garantindo que o banco de dados esteja acessível apenas para os serviços que precisam dele.
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan migrate --force
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fdo_network
    restart: "no"
    # Este serviço é projetado para ser executado uma única vez para aplicar as migrações. Ele pode ser removido 
    # ou comentado após a execução inicial.