user  nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Configurações de DNS para resolver nomes de host dentro do contêiner Docker
    # Isso evita problemas de cache de DNS e garante que o Nginx possa resolver nomes de host corretamente.
    resolver 127.0.0.11 valid=30s;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Logs (opcional)
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    limit_req_zone $binary_remote_addr zone=api:10m rate=20r/s;
    server_tokens off;
    proxy_hide_header X-Powered-By;
    fastcgi_hide_header X-Powered-By;
    client_max_body_size 10M;

    # proxy_intercept_errors on;

    error_page 500 502 503 504 /50x.html;
    error_page 404 /404.html;
    
    # Define quais métodos são permitidos (1 = Permitido, 0 = Bloqueado)
    map $request_method $is_method_allowed {
        default 0;
        GET     1;
        HEAD    1;
        POST    1;
        PUT     1;
        PATCH   1;
        DELETE  1;
        OPTIONS 1;
    }

    # Importa os sites
    include /etc/nginx/conf.d/*.conf;
}